repository:
  name: django-ecs-simple-deploy
  description: Django ECS Simple Deploy
  private: true
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      required_status_checks:
        strict: true
        contexts: ["deploy"]
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: []
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      required_signatures: false
      lock_branch: false
      allow_fork_syncing: true
      required_deployments:
        - production
      required_branches:
        - develop

  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      required_status_checks:
        strict: true
        contexts: ["deploy"]
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: []
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      required_signatures: false
      lock_branch: false
      allow_fork_syncing: true 