version: '3'

services:
  # Djangoアプリケーション
  django-app:
    image: python:3.11-slim
    platform: linux/amd64
    volumes:
      - ./app:/app
    working_dir: /app
    expose:
      - "8000"
    command: >
      bash -c "pip install -r requirements.txt &&
               pip install django boto3 celery django-environ gunicorn &&
               if [ ! -f manage.py ]; then django-admin startproject config . && python manage.py migrate; fi &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - ALLOWED_HOSTS=*
      - DJANGO_SETTINGS_MODULE=config.settings
      - AWS_REGION=ap-northeast-1
    env_file:
      - .env
    networks:
      - app-network

  # Nginx プロキシ（Basic認証付き）
  nginx-proxy:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django-app
    volumes:
      - ./app/staticfiles:/app/staticfiles:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
