AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple Django ECS Service for Staging'

Parameters:
  ImageUrl:
    Type: String
    Description: The URL of the Docker image to run
    Default: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/django-ecs-app:latest

Resources:
  # ECS Task Definition
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: django-app-staging-simple
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue:
          !Sub 'django-ecs-cluster-staging-v2-ECSTaskExecutionRole'
      TaskRoleArn:
        Fn::ImportValue:
          !Sub 'django-ecs-cluster-staging-v2-ECSTaskExecutionRole'
      ContainerDefinitions:
        - Name: django-app
          Image: !Ref ImageUrl
          Essential: true
          PortMappings:
            - ContainerPort: 8000
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: "/ecs/django-app-staging"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: django-app
          Environment:
            - Name: DEBUG
              Value: '1'
            - Name: ALLOWED_HOSTS
              Value: '*'
            - Name: DJANGO_SETTINGS_MODULE
              Value: 'config.settings'
            - Name: SECRET_KEY
              Value: 'django-insecure-temporary-key-for-staging'

  # ECS Service (ALBなし、パブリックIP直接アクセス)
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: django-ecs-service-staging-simple
      Cluster:
        Fn::ImportValue:
          !Sub 'django-ecs-cluster-staging-v2-ECSCluster'
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::ImportValue:
                !Sub 'django-ecs-cluster-staging-v2-ECSPublicSecurityGroup'
          Subnets:
            - Fn::ImportValue:
                !Sub 'django-ecs-cluster-staging-v2-PublicSubnet1'
            - Fn::ImportValue:
                !Sub 'django-ecs-cluster-staging-v2-PublicSubnet2'

Outputs:
  Service:
    Description: The ECS Service
    Value: !Ref Service
    Export:
      Name: !Sub "${AWS::StackName}-Service"
      
  TaskDefinition:
    Description: The Task Definition
    Value: !Ref TaskDefinition
    Export:
      Name: !Sub "${AWS::StackName}-TaskDefinition" 