AWSTemplateFormatVersion: '2010-09-09'
Description: 'Django ECS Service for Staging using Unified Production ALB'

Parameters:
  ImageUrl:
    Type: String
    Description: The URL of the Docker image to run
    Default: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/django-ecs-app:latest
  
  ProductionALBArn:
    Type: String
    Description: The ARN of the production ALB to use
    Default: arn:aws:elasticloadbalancing:ap-northeast-1:026090540679:loadbalancer/app/django-Appli-21kFlF5Lv7wZ/aa6dffce814c1a0b
  
  ProductionHTTPSListenerArn:
    Type: String
    Description: The ARN of the production HTTPS listener
    Default: ""  # 自動取得されます

Resources:
  # ECS Task Definition
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: django-app-staging-unified
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue:
          !Sub 'django-ecs-cluster-staging-v2-ECSTaskExecutionRole'
      TaskRoleArn:
        Fn::ImportValue:
          !Sub 'django-ecs-cluster-staging-v2-ECSTaskExecutionRole'
      ContainerDefinitions:
        - Name: django-app
          Image: !Ref ImageUrl
          Essential: true
          PortMappings:
            - ContainerPort: 8000
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: "/ecs/django-app-staging-unified"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          Environment:
            - Name: ALLOWED_HOSTS
              Value: 'staging.grape-app.jp,localhost,127.0.0.1'
            - Name: DJANGO_SETTINGS_MODULE
              Value: 'config.settings'
            - Name: SECRET_KEY
              Value: 'django-insecure-temporary-key-for-staging'
            - Name: DEBUG
              Value: "False"
            - Name: HTTPS_ENABLED
              Value: "True"

  # Target Group for Staging
  StagingTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: django-staging-unified-tg
      Port: 8000
      Protocol: HTTP
      VpcId:
        Fn::ImportValue:
          !Sub 'django-ecs-cluster-staging-v2-VPC'
      TargetType: ip
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /health/
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3

  # Staging HTTPS Listener Rule
  StagingHTTPSListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref StagingTargetGroup
      Conditions:
        - Field: host-header
          Values:
            - staging.grape-app.jp
      ListenerArn: arn:aws:elasticloadbalancing:ap-northeast-1:026090540679:listener/app/django-Appli-21kFlF5Lv7wZ/aa6dffce814c1a0b/074eae0b43a4902e
      Priority: 110

  # Staging HTTP Listener Rule (for redirect)
  StagingHTTPListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: 443
            StatusCode: HTTP_301
      Conditions:
        - Field: host-header
          Values:
            - staging.grape-app.jp
      ListenerArn: arn:aws:elasticloadbalancing:ap-northeast-1:026090540679:listener/app/django-Appli-21kFlF5Lv7wZ/aa6dffce814c1a0b/51594e378d3fadf6
      Priority: 110

  # ECS Service with Production ALB Integration
  Service:
    Type: AWS::ECS::Service
    DependsOn: 
      - StagingHTTPSListenerRule
      - StagingHTTPListenerRule
    Properties:
      ServiceName: django-ecs-service-staging-unified
      Cluster:
        Fn::ImportValue:
          !Sub 'django-ecs-cluster-staging-v2-ECSCluster'
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue:
                !Sub 'django-ecs-cluster-staging-v2-ECSSecurityGroup'
          Subnets:
            - Fn::ImportValue:
                !Sub 'django-ecs-cluster-staging-v2-PrivateSubnet1'
            - Fn::ImportValue:
                !Sub 'django-ecs-cluster-staging-v2-PrivateSubnet2'
      LoadBalancers:
        - ContainerName: django-app
          ContainerPort: 8000
          TargetGroupArn: !Ref StagingTargetGroup

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/ecs/django-app-staging-unified"
      RetentionInDays: 14

Outputs:
  Service:
    Description: The ECS Service with Unified ALB
    Value: !Ref Service
    Export:
      Name: !Sub "${AWS::StackName}-Service"
      
  TargetGroup:
    Description: The Target Group for Staging
    Value: !Ref StagingTargetGroup
    Export:
      Name: !Sub "${AWS::StackName}-TargetGroup"
      
  StagingHTTPSListenerRule:
    Description: The HTTPS Listener Rule for Staging
    Value: !Ref StagingHTTPSListenerRule
    Export:
      Name: !Sub "${AWS::StackName}-HTTPSListenerRule" 