# Generated by Django 5.2 on 2025-06-19 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='記事番号')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('pending', '申請中'), ('rejected', '承認NG'), ('approved', '承認済'), ('sent', '送信済'), ('published', '公開済'), ('unknown', '不明')], default='draft', max_length=20, verbose_name='ステータス')),
                ('title', models.CharField(max_length=200, verbose_name='記事タイトル')),
                ('content', models.TextField(verbose_name='記事内容・概要')),
                ('reference_url', models.URLField(blank=True, verbose_name='参考URL')),
                ('facebook_text', models.TextField(blank=True, verbose_name='Facebook投稿テキスト')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_articles', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_articles', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_articles', to=settings.AUTH_USER_MODEL, verbose_name='ライター')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='アクション')),
                ('old_value', models.TextField(blank=True, verbose_name='変更前')),
                ('new_value', models.TextField(blank=True, verbose_name='変更後')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='変更日時')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='article_management.article', verbose_name='記事')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='変更者')),
            ],
            options={
                'verbose_name': '記事履歴',
                'verbose_name_plural': '記事履歴',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_name', models.CharField(help_text='例: @username', max_length=100, verbose_name='ハンドルネーム')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20, verbose_name='プラットフォーム')),
                ('profile_url', models.URLField(blank=True, verbose_name='プロフィールURL')),
                ('status', models.CharField(choices=[('ok', 'OK（使用可）'), ('ng', 'NG（使用不可）')], default='ok', max_length=10, verbose_name='ステータス')),
                ('permission_date', models.DateField(blank=True, null=True, verbose_name='許諾取得日')),
                ('permission_expires', models.DateField(blank=True, help_text='期限がない場合は空欄', null=True, verbose_name='許諾期限')),
                ('usage_conditions', models.TextField(blank=True, help_text='クレジット表記など特別な条件', verbose_name='利用条件')),
                ('ng_reason', models.TextField(blank=True, help_text='NGの場合の理由を記載', verbose_name='NG理由')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'SNSユーザー',
                'verbose_name_plural': 'SNSユーザー',
                'ordering': ['-created_at'],
                'unique_together': {('handle_name', 'platform')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='social_media_users',
            field=models.ManyToManyField(blank=True, related_name='articles', to='article_management.socialmediauser', verbose_name='使用SNSユーザー'),
        ),
    ]
