# Generated by Django 5.2 on 2025-06-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='social_media_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID（IGは手打ち）'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reference_url',
            field=models.URLField(blank=True, verbose_name='記事URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pending', '申請中'), ('through', 'スルー'), ('ng', '掲載NG'), ('need_permission', '要許可'), ('no_apply', '申請不要'), ('published', '公開済'), ('unknown', '不明')], default='draft', max_length=20, verbose_name='ステータス'),
        ),
    ]
