# Generated by Django 5.2 on 2025-06-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_management', '0002_article_social_media_id_alter_article_reference_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateSNSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='企業名')),
                ('account_name', models.CharField(max_length=100, verbose_name='アカウント名')),
                ('platform', models.CharField(choices=[('twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('threads', 'Threads'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('blog', 'ブログ')], max_length=20, verbose_name='プラットフォーム')),
                ('url', models.URLField(verbose_name='URL')),
                ('sales_status', models.CharField(choices=[('ok', 'OK'), ('checking', '確認中'), ('ng', 'NG')], default='checking', max_length=20, verbose_name='営業ステータス')),
                ('editorial_status', models.CharField(choices=[('ok', 'OK'), ('checking', '確認中'), ('ng', 'NG')], default='checking', max_length=20, verbose_name='編集ステータス')),
                ('require_prior_approval', models.BooleanField(default=False, verbose_name='事前確認必須')),
                ('require_post_report', models.BooleanField(default=False, verbose_name='事後報告必須')),
                ('embed_only', models.BooleanField(default=False, verbose_name='埋め込みのみ')),
                ('allow_image_download', models.BooleanField(default=True, verbose_name='画像DL可')),
                ('allow_screenshot', models.BooleanField(default=True, verbose_name='スクショ可')),
                ('credit_format', models.CharField(blank=True, max_length=200, verbose_name='クレジット表記形式')),
                ('excluded_content', models.TextField(blank=True, verbose_name='使用不可コンテンツ')),
                ('special_conditions', models.TextField(blank=True, verbose_name='特殊条件')),
                ('primary_contact', models.TextField(verbose_name='主要連絡先')),
                ('pr_agency', models.TextField(blank=True, verbose_name='PR会社情報')),
                ('contact_notes', models.TextField(blank=True, verbose_name='連絡時の注意事項')),
                ('notes', models.TextField(blank=True, verbose_name='補足')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '企業SNSアカウント',
                'verbose_name_plural': '企業SNSアカウント',
                'ordering': ['company_name', 'account_name'],
                'unique_together': {('company_name', 'account_name', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='PersonalSNSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_name', models.CharField(max_length=100, verbose_name='ハンドルネーム')),
                ('real_name', models.CharField(blank=True, max_length=100, verbose_name='本名')),
                ('platform', models.CharField(choices=[('twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('threads', 'Threads'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('blog', 'ブログ')], max_length=20, verbose_name='プラットフォーム')),
                ('url', models.URLField(verbose_name='プロフィールURL')),
                ('status', models.CharField(choices=[('ok', 'OK（使用可）'), ('conditional', '条件付きOK'), ('ng', 'NG（使用不可）')], default='ok', max_length=20, verbose_name='ステータス')),
                ('status_date', models.DateField(auto_now_add=True, verbose_name='ステータス変更日')),
                ('category', models.CharField(blank=True, choices=[('manga', '漫画ネタ'), ('animal', '動物ネタ'), ('celebrity', '芸能人'), ('other', 'その他')], max_length=20, verbose_name='カテゴリ')),
                ('reason', models.TextField(blank=True, verbose_name='NG理由/条件')),
                ('conditions', models.TextField(blank=True, verbose_name='利用条件')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '個人SNSアカウント',
                'verbose_name_plural': '個人SNSアカウント',
                'ordering': ['handle_name'],
                'unique_together': {('handle_name', 'platform')},
            },
        ),
    ]
