# Generated by Django 5.2 on 2025-06-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_management', '0003_corporatesnsaccount_personalsnsaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pending', '申請中'), ('through', 'スルー'), ('ng', '掲載NG'), ('need_permission', '要許可'), ('no_apply', '申請不要'), ('published', '公開済'), ('info_provided', '情報提供'), ('-', '-'), ('post_report', '事後報告'), ('original', '独自記事')], default='draft', max_length=20, verbose_name='ステータス'),
        ),
    ]
