# Generated by Django 5.2 on 2025-06-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_management', '0004_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='report_status',
            field=models.CharField(choices=[('not_required', '不要'), ('sent', '送信済み'), ('ready_with_x', '準備完了Xあり'), ('ready_without_x', '準備完了Xなし')], default='not_required', max_length=20, verbose_name='掲載報告'),
        ),
    ]
