# Generated by Django 5.2 on 2025-06-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_management', '0005_article_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='grape_article_url',
            field=models.URLField(blank=True, verbose_name='グレイプ記事リンク'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reference_url',
            field=models.URLField(blank=True, verbose_name='参照ネタURL'),
        ),
    ]
