# Generated by Django 5.2 on 2025-05-22 01:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProofreadingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(verbose_name='原文')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '校正リクエスト',
                'verbose_name_plural': '校正リクエスト',
            },
        ),
        migrations.CreateModel(
            name='ReplacementDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_word', models.CharField(max_length=255, verbose_name='元の語句')),
                ('replacement_word', models.CharField(max_length=255, verbose_name='置換後の語句')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '置換辞書',
                'verbose_name_plural': '置換辞書',
            },
        ),
        migrations.CreateModel(
            name='ProofreadingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_text', models.TextField(verbose_name='校正後テキスト')),
                ('completion_time', models.FloatField(blank=True, null=True, verbose_name='処理時間(秒)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='proofreading_ai.proofreadingrequest')),
            ],
            options={
                'verbose_name': '校正結果',
                'verbose_name_plural': '校正結果',
            },
        ),
    ]
