# Generated by Django 5.2 on 2025-05-28 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofreading_ai', '0002_companydictionary_correctionv2_geographicdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='InconsistencyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='項目名')),
                ('type', models.CharField(choices=[('geographic', '地理的矛盾'), ('temporal', '時系列矛盾'), ('numerical', '数値矛盾'), ('logical', '論理的矛盾'), ('factual', '事実矛盾')], max_length=20, verbose_name='種別')),
                ('correct_form', models.CharField(blank=True, max_length=255, verbose_name='正しい形')),
                ('incorrect_patterns', models.TextField(blank=True, help_text='カンマ区切りで複数指定可能', verbose_name='誤りパターン')),
                ('description', models.TextField(blank=True, help_text='矛盾の詳細や背景情報', verbose_name='説明')),
                ('detection_rule', models.TextField(blank=True, help_text='矛盾を検出するためのルールや条件', verbose_name='検出ルール')),
                ('severity', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='重要度')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '矛盾検出データ',
                'verbose_name_plural': '矛盾検出データ',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='correctionv2',
            name='category',
            field=models.CharField(choices=[('tone', '言い回しアドバイス'), ('typo', '誤字修正'), ('dict', '社内辞書ルール'), ('inconsistency', '矛盾チェック')], max_length=15, verbose_name='カテゴリー'),
        ),
        migrations.DeleteModel(
            name='GeographicData',
        ),
    ]
