name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pytest pytest-django flake8 bandit
        pip install --upgrade ruff

    - name: Check Ruff version
      run: python -m ruff --version

    - name: Filter Python changes
      id: changes
      uses: dorny/paths-filter@v2
      with:
        filters: |
          python:
            - '**/*.py'

    - name: Show change detection result
      run: |
        echo "Python files changed: ${{ steps.changes.outputs.python }}"

    - name: Skip tests
      if: steps.changes.outputs.python == 'false'
      run: echo "No Python files changed, skipping tests."

    - name: Apply auto-format with ruff
      if: steps.changes.outputs.python == 'true'
      run: python -m ruff format app

    - name: Run tests
      if: steps.changes.outputs.python == 'true'
      run: python -m pytest --verbose --maxfail=5
        
    - name: Lint with flake8
      if: steps.changes.outputs.python == 'true'
      run: |
        flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Lint with ruff
      if: steps.changes.outputs.python == 'true'
      run: python -m ruff check app
        
    - name: Security check with bandit
      if: steps.changes.outputs.python == 'true'
      run: |
        bandit -r app -x app/tests 
    - name: Notify Slack
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
        mention: 'here'
        if_mention: failure
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      continue-on-error: true 