# Generated by Django 5.2 on 2025-05-15 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='grapecheck.category', verbose_name='親カテゴリ')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrapeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField(verbose_name='評価テキスト')),
                ('total_score', models.IntegerField(verbose_name='総合スコア')),
                ('writing_style_score', models.IntegerField(verbose_name='文体スコア')),
                ('structure_score', models.IntegerField(verbose_name='構成スコア')),
                ('keyword_score', models.IntegerField(verbose_name='キーワードスコア')),
                ('improvement_suggestions', models.TextField(verbose_name='改善提案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grapecheck.category', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': 'グレイプらしさ評価',
                'verbose_name_plural': 'グレイプらしさ評価',
                'ordering': ['-created_at'],
            },
        ),
    ]
