# Generated by Django 5.2 on 2025-05-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapecheck', '0001_initial'),
    ]

    operations = [
    ]
